# Generated by Django 5.1.1 on 2024-10-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='images',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
    ]
