# Generated by Django 5.1.1 on 2024-10-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_alter_articleimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='images',
            field=models.ImageField(upload_to='images/', verbose_name='Фото'),
        ),
    ]
