# Generated by Django 5.1.1 on 2024-10-21 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_alter_articleimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default-slug', verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
